apiVersion: apps/v1
kind: Deployment
metadata:
  name: gucat-web-deployment
  namespace: gucat-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gucat-web
  template:
    metadata:
      labels:
        app: gucat-web
    spec:
      containers:
      - name: gucat-web
        image: qblyxs/gucat-web:1.1.0-dev
        ports:
        - containerPort: 4000