apiVersion: apps/v1
kind: Deployment
metadata:
  name: gucat-web-deployment
  namespace: gucat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gucat-web
  template:
    metadata:
      labels:
        app: gucat-web
    spec:
      nodeSelector:
        memos: enable
      containers:
      - name: gucat-web
        image: qblyxs/gucat-web:1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
---